GameStore/Models/DTO/Statistical.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GameStore.Models.DTO
{
    public class Statistical
    {
        public string NameKH { get; set; }
        public string Namegame { get; set; }
        public int Quantity { get; set; }
        public float PriceGame { get; set; }
        public float Total { get; set; }

    }
}

GameStore/Areas/Admin/Controllers/TrangChuAdminController.cs
using GameStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Models.DTO;
using GameStore.Models.DTO.GameModel;
using Newtonsoft.Json;

namespace GameStore.Areas.Admin.Controllers
{
    public class TrangChuAdminController : Controller
    {
        // GET: Admin/TrangChuAdmin
        GameStoreDataContext db = new GameStoreDataContext();

        // GET: Admin/TrangChu
        public ActionResult Index()
        {
            DateTime today = DateTime.Today;
            DateTime yesterday = DateTime.Today.AddDays(-1);
            ViewBag.SoluongOL = db.KHACHHANGs.Where(m=>m.LastActivity == true).Count();
            
            ViewBag.TongDoanhThu = db.DONHANGs.Where(m =>m.NgayMua.Value.Date == today).Sum(m=>m.TongTien);
            ViewBag.TongDoanhThuHomQua = db.DONHANGs.Where(m => m.NgayMua != null && m.NgayMua.Value.Date == yesterday).Sum(m => m.TongTien);
            return View();
        }

        public ActionResult NavPartial()
        {
            return PartialView();
        }

        public ActionResult NavBarPartial()
        {
            return PartialView();
        }

        public ActionResult FootPartial()
        {
            return PartialView();
        }

        public ActionResult NavigationPartial()
        {
            return PartialView();
        }
        public JsonResult GetOnlineUserCount()
        {
            int onlineUserCount = db.KHACHHANGs.Where(m => m.LastActivity == true).Count(); 

            return Json(new { onlineUserCount }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetSLBuyGame()
        {
            // Lấy ngày hôm nay
            DateTime today = DateTime.Today;

            // Lấy số lượng đơn hàng mua trong ngày hôm nay
            int numberOfOrders = db.DONHANGs.Count(m => m.NgayMua.Value.Date == today);
            return Json(new { numberOfOrders }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTotalToday()
        {
            // Lấy ngày hôm nay
            DateTime today = DateTime.Today;

            // Lấy số lượng đơn hàng mua trong ngày hôm nay
            var numberOfSumTotal = db.DONHANGs.Where(m =>m.NgayMua.Value.Date == today).Sum(m => m.TongTien);
            return Json(new { numberOfSumTotal }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTotalYesterday()
        {
            // Lấy ngày hôm qua
            DateTime yesterday = DateTime.Today.AddDays(-1);

            // Lấy số lượng đơn hàng mua trong ngày hôm qua
            var totalAmountYesterday = db.DONHANGs.Where(m => m.NgayMua != null && m.NgayMua.Value.Date == yesterday).Sum(m => m.TongTien);

            return Json(new { totalAmountYesterday }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Statistical()
        {
            List<Statistical> list = new List<Statistical>();
            var kh = db.KHACHHANGs.ToList();
            foreach(var item in kh)
            {
                if(item.ListGameInLibrary == null)
                {
                    Statistical listgame = new Statistical { 
                        NameKH = item.HoTen,
                        Namegame ="Chưa Mua",
                        
                    };
                    list.Add(listgame);
                }
                else {
                    List<GamesInCart> listgame = JsonConvert.DeserializeObject<List<GamesInCart>>(item.ListGameInLibrary);
                    if (listgame != null)
                    {
                        foreach (var i in listgame)
                        {
                            Statistical st = new Statistical
                            {
                                NameKH = item.HoTen,
                                Namegame = i.Name,
                                Quantity = i.Quantity,
                                PriceGame = i.PriceGame,
                                Total = i.Quantity * i.PriceGame
                            };
                            list.Add(st);
                        }
                    }
                }                                          
            }    
            return View(list);
        }
    }
}

GameStore/Areas/Admin/Views/TrangChuAdmin/FootPartial.cshtml
<div class="row align-items-center justify-content-xl-between">
    <div class="col-xl-6">
        <div class="copyright text-center text-xl-left text-muted">
            &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
        </div>
    </div>

</div>

GameStore/Areas/Admin/Views/TrangChuAdmin/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        Dashboard Admin
    </title>
    <script src=" https://cdn.jsdelivr.net/npm/canvas-confetti@1.5.1/dist/confetti.browser.min.js "></script>
    <!-- Favicon -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
</head>

<body class="">

    <div class="main-content">

        <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
            <div class="container-fluid">
                <div class="header-body">
                    <!-- Card stats -->
                    <div class="row">
                        <div class="col-xl-3 col-lg-6">
                            <div class="card card-stats mb-4 mb-xl-0">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <h5 class="card-title text-uppercase text-muted mb-0">Games Buy</h5>
                                            <span class="h2 font-weight-bold mb-0" id="SLBuyGame"></span>
                                        </div>
                                        <div class="col-auto">
                                            <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                                                <i class="fas fa-chart-pie"></i>

                                            </div>
                                        </div>
                                    </div>
                                    <p class="mt-3 mb-0 text-muted text-sm">

                                        <span class="text-nowrap">Today</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-6">
                            <div class="card card-stats mb-4 mb-xl-0">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <h5 class="card-title text-uppercase text-muted mb-0">Users Online</h5>
                                            <span class="h2 font-weight-bold mb-0" id="updatesl">@ViewBag.SoluongOL</span>
                                        </div>
                                        <div class="col-auto">
                                            <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
                                                <i class="fas fa-users"></i>

                                            </div>
                                        </div>
                                    </div>
                                    <p class="mt-3 mb-0 text-muted text-sm">

                                        <span class="text-nowrap">Login last three minutes ago</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-6">
                            <div class="card card-stats mb-4 mb-xl-0">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <h5 class="card-title text-uppercase text-muted mb-0">Total Today</h5>
                                            @if (@ViewBag.TongDoanhThu == null)
                                            {
                                                <span class="h2 font-weight-bold mb-0" id="Sumtotal">0 $</span>
                                            }
                                            else
                                            {
                                                <span class="h2 font-weight-bold mb-0" id="Sumtotal">@ViewBag.TongDoanhThu $</span>
                                            }

                                        </div>
                                        <div class="col-auto">
                                            <div class="icon icon-shape bg-info text-white rounded-circle shadow">
                                                <i class="fas fa-chart-bar"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <p class="mt-3 mb-0 text-muted text-sm">

                                        <span class="text-nowrap">Today</span>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-6">
                            <div class="card card-stats mb-4 mb-xl-0">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col">
                                            <h5 class="card-title text-uppercase text-muted mb-0">Total Yesterday</h5>
                                            @if (@ViewBag.TongDoanhThuHomQua == null)
                                            {
                                                <span class="h2 font-weight-bold mb-0" id="Totalyesterday">0 $</span>
                                            }
                                            else
                                            {
                                                <span class="h2 font-weight-bold mb-0" id="Totalyesterday">@ViewBag.TongDoanhThuHomQua $</span>
                                            }
                                        </div>
                                        <div class="col-auto">
                                            <div class="icon icon-shape bg-yellow text-white rounded-circle shadow">
                                                <i class="fas fa-chart-bar"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <p class="mt-3 mb-0 text-muted text-sm">

                                        <span class="text-nowrap">Since yesterday</span>
                                    </p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col-xl-8 mb-5 mb-xl-0">
                    <div class="card bg-gradient-default shadow">
                        <div class="card-header bg-transparent">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h6 class="text-uppercase text-light ls-1 mb-1">Overview</h6>
                                    <h2 class="text-white mb-0">Sales value</h2>
                                </div>
                                <div class="col">
                                    <ul class="nav nav-pills justify-content-end">
                                        <li class="nav-item mr-2 mr-md-0" data-toggle="chart" data-target="#chart-sales" data-update='{"data":{"datasets":[{"data":[0, 20, 10, 30, 15, 40, 20, 60, 60]}]}}' data-prefix="$" data-suffix="k">
                                            <a href="#" class="nav-link py-2 px-3 active" data-toggle="tab">
                                                <span class="d-none d-md-block">Month</span>
                                                <span class="d-md-none">M</span>
                                            </a>
                                        </li>
                                        <li class="nav-item" data-toggle="chart" data-target="#chart-sales" data-update='{"data":{"datasets":[{"data":[0, 20, 5, 25, 10, 30, 15, 40, 40]}]}}' data-prefix="$" data-suffix="k">
                                            <a href="#" class="nav-link py-2 px-3" data-toggle="tab">
                                                <span class="d-none d-md-block">Week</span>
                                                <span class="d-md-none">W</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <!-- Chart -->
                            <div class="chart">
                                <!-- Chart wrapper -->
                                <canvas id="chart-sales" class="chart-canvas"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4">
                    <div class="card shadow">
                        <div class="card-header bg-transparent">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h6 class="text-uppercase text-muted ls-1 mb-1">Performance</h6>
                                    <h2 class="mb-0">Total orders</h2>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <!-- Chart -->
                            <div class="chart">
                                <canvas id="chart-orders" class="chart-canvas"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script>
        // Hàm để cập nhật số lượng online user
        function updateOnlineUserCount() {
            $.ajax({
                url: '/Admin/TrangChuAdmin/GetOnlineUserCount',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    $('#updatesl').text(data.onlineUserCount)

                },
                error: function () {
                    // Xử lý lỗi nếu cần
                }
            });
        }
        // Hàm để cập nhật số lượng mua game
        function updateNumberOfOrders() {
            $.ajax({
                /**/
                url: '/Admin/TrangChuAdmin/GetSLBuyGame',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    $('#SLBuyGame').text(data.numberOfOrders);
                },
                error: function () {
                    // Xử lý lỗi nếu cần
                }
            });
        }
        function updateNumberOfSumTotal() {
            $.ajax({
                /**/
                url: '/Admin/TrangChuAdmin/GetTotalToday',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    if (data.numberOfSumTotal == null) {
                        $('#Sumtotal').text('0 $');
                    }
                    else { $('#Sumtotal').text(data.numberOfSumTotal + ' $'); }

                },
                error: function () {
                    // Xử lý lỗi nếu cần
                }
            });
        }
        function updateNumberOfSumTotalYesterday() {
            $.ajax({
                /**/
                url: '/Admin/TrangChuAdmin/GetTotalTodayYesterday',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    $('#Totalyesterday').text(data.numberOfSumTotal + ' $');
                },
                error: function () {
                    // Xử lý lỗi nếu cần
                }
            });
        }
        setInterval(updateOnlineUserCount, 3000);
        setInterval(updateNumberOfOrders, 900);
        setInterval(updateNumberOfSumTotal, 3000);
        setInterval(updateNumberOfSumTotalYesterday, 3000);
    </script>
    <script>
        var duration = 1 * 1000;
        var end = Date.now() + duration;

        (function frame() {
            // launch a few confetti from the left edge
            confetti({
                particleCount: 7,
                angle: 60,
                spread: 55,
                origin: { x: 0 }
            });
            // and launch a few from the right edge
            confetti({
                particleCount: 7,
                angle: 120,
                spread: 55,
                origin: { x: 1 }
            });

            // keep going until we are out of time
            if (Date.now() < end) {
                requestAnimationFrame(frame);
            }
        }());
    </script>
</body>

</html>

GameStore/Areas/Admin/Views/TrangChuAdmin/NavBarPartial.cshtml
@using GameStore.Models
@{
    ADMIN admin = Session["Admin"] as ADMIN;
}

<div class="container-fluid">
    <!-- Brand -->
    <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="@Url.Action("Index", "TrangChuAdmin")">Dashboard</a>
    <!-- Form -->
    <form class="navbar-search navbar-search-dark form-inline mr-3 d-none d-md-flex ml-lg-auto">
        <div class="form-group mb-0">
            <div class="input-group input-group-alternative">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                </div>
                <input class="form-control" placeholder="Search" type="text">
            </div>
        </div>
    </form>
    <!-- User -->
    <ul class="navbar-nav align-items-center d-none d-md-flex">
        @if (admin != null)
        {       
            <li class="nav-item dropdown">
                <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <div class="media-body ml-2 d-none d-lg-block">
                            <span class="mb-0 text-sm font-weight-bold">Welcome: @admin.HoTen</span>
                        </div>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class="dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome!</h6>
                    </div>
                    <a href="@Url.Action("Profile", "Profile")" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>My profile</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="@Url.Action("Logout", "LoginAdmin")" class="dropdown-item">
                        <i class="ni ni-user-run"></i>
                        <span>Logout</span>
                    </a>
                </div>
            </li>
        }
    </ul>
</div>

GameStore/Areas/Admin/Views/TrangChuAdmin/NavPartial.cshtml
@using GameStore.Models
@{
    ADMIN admin = Session["Admin"] as ADMIN;
}
<li class="nav-item  active ">
    <a class="nav-link  active " href="@Url.Action("Index","TrangChuAdmin")">
        <i class="ni ni-tv-2 text-primary"></i> Dashboard
    </a>
</li>
@if (admin != null)
{
    <li class="nav-item">
        <a class="nav-link " href="@Url.Action("Profile", "Profile")">
            <i class="ni ni-single-02 text-yellow"></i> My profile
        </a>
    </li>
}
    <li class="nav-item">
        <a class="nav-link " href="@Url.Action("QLGames", "QLGame")">
            <i class="ni ni-bullet-list-67 text-red"></i> Game
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="@Url.Action("VerifiedPost", "AdCommunity")">
            <i class="ni ni-album-2 text-green"></i> Community
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link " href="@Url.Action("Statistical", "TrangChuAdmin")">
            <i class="ni ni-chart-bar-32 text-orange"></i>
            Statistical
        </a>
    </li>

GameStore/Areas/Admin/Views/TrangChuAdmin/NavigationPartial.cshtml
<li class="nav-item">
    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html">
        <i class="ni ni-spaceship"></i> Getting started
    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html">
        <i class="ni ni-palette"></i> Foundation
    </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html">
        <i class="ni ni-ui-04"></i> Components
    </a>
</li>

GameStore/Areas/Admin/Views/TrangChuAdmin/Statistical.cshtml
@model IEnumerable<GameStore.Models.DTO.Statistical>

@{
    ViewBag.Title = "Statistical";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>




<h2 style="text-align:center">Statistical</h2>

<style>
    .data_table {
        background: #fff;
        padding: 15px;
        box-shadow: 1px 3px 5px #aaa;
        border-radius: 5px;
    }
</style>


<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="data_table">
                <table id="example" class="table table-striped table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>
                                @Html.DisplayName("Customer name")
                            </th>
                            <th>
                                @Html.DisplayName("Name Game")
                            </th>
                            <th>
                                @Html.DisplayName("Quantity")
                            </th>
                            <th>
                                @Html.DisplayName("Price Game")
                            </th>
                            <th>
                                @Html.DisplayName("Total")
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NameKH)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Namegame)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PriceGame)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Total)
                                </td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



<script>
    $(document).ready(function () {
        var table = $("#example").DataTable({
            buttons: [
                {
                    extend: 'copy',
                    text: 'Copy',
                    filename: 'Danh_sach_khach_hang_mua_game_' + getCurrentDate(),
                    charset: 'utf-8', // Add this line
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }
                },
                {
                    extend: 'csv',
                    text: 'CSV',
                    filename: 'Danh_sach_khach_hang_mua_game_' + getCurrentDate(),
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }  
                },
                {
                    extend: 'excel',
                    text: 'Excel',
                    filename: 'Danh_sach_khach_hang_mua_game_' + getCurrentDate(),
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }
                },
                {
                    extend: 'pdf',
                    text: 'PDF',
                    filename: 'Danh_sach_khach_hang_mua_game_' + getCurrentDate(),
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }
                },
                {
                    extend: 'print',
                    text: 'Print',
                    filename: 'Danh_sach_khach_hang_mua_game_' + getCurrentDate(),
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4]
                    }
                }
            ]
        });
        table.buttons().container().appendTo('#example_wrapper .col-md-6:eq(0)');
    });
    function getCurrentDate() {
        var today = new Date();
        var year = today.getFullYear();
        var month = (today.getMonth() + 1).toString().padStart(2, '0');
        var day = today.getDate().toString().padStart(2, '0');
        return year + month + day;
    }
</script>